# Generated by Django 4.2.1 on 2023-05-29 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("event_name", models.CharField(max_length=255)),
                ("data", models.TextField()),
                ("time", models.DateTimeField()),
                ("image", models.ImageField(null=True, upload_to="images")),
                ("location", models.CharField(max_length=255)),
                ("isLiked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("likecount", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "events",
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
